# Project: Project1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = "dashboard\ project.o" $(RES)
LINKOBJ  = "dashboard project.o" $(RES)
LIBS =  -L"C:/Dev-Cpp/lib"  
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = "dashboard project1.exe"
CXXFLAGS = $(CXXINCS)   -fshort-double
CFLAGS = $(INCS)   -fshort-double
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before "dashboard project1.exe" all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "dashboard project1.exe" $(LIBS)

"dashboard\ project.o": dashboard\ project.cpp
	$(CPP) -c "dashboard project.cpp" -o "dashboard project.o" $(CXXFLAGS)
